### ISSUE TITLE
Panels glitch on iOS9 (KeyboardShrinksView = true)

### ISSUE THREAD

**Issue by TCattd** [phonon-framework/phonon#153]
Hello again :)

iOS9 bugs... again. Haven't dig any further on this issue, but i know why it happens.

If you set KeyboardShrinksView to true inside a cordova app, Phonon's panels on iOS9 looks like this: http://i.imgur.com/qbUQ27b.png
Note the transparent space just right where the webview ends and the keyboard appears.

But if i change KeyboardShrinksView to false, they (panels) looks ok: http://i.imgur.com/hpSjMkQ.png

KeyboardShrinksView = true behaviour makes sense for an app, so it behaves just like other apps that shrink the view when the keyboard is shown (ex: http://i.imgur.com/t5okgOC.png ), so it would be ideal to have KeyboardShrinksView to true inside a cordova app.

**Comment by Qathom** [comment]
Hi @TCattd,

Thank you for opening this issue.
I am not 100% sure that it concerns Phonon directly.
Have you tried the [Cordova keyboard plugin](https://github.com/apache/cordova-plugins/tree/master/keyboard)?
You can use `Keyboard.shrinkView(true);`.

Does it fix your problem?

**Comment by TCattd** [comment]
Hi,

The issue is not about the shrinking on Cordova. It works fine on the app.
The issue is about this visual glitch on a full panel on Phonon: http://prntscr.com/c4zzpd

I have configured the plugin properly and the webview shrinks ok when the keyboard is shown, no issues with that. But enabling the webview shrinking make the full panels glitch on iOS9 as the screenshot.

That glitch doesn't happens if i remove the shrinking (the other screenshot: http://i.imgur.com/hpSjMkQ.png ).

**Comment by Qathom** [comment]
Hi @TCattd,

Thank you for the precision.
This is strange.. I don't understand why this is happening.

Can you please try this:

```css
.panel {
    -webkit-backface-visibility: hidden;
}

Another idea is to change the value of the meta viewport like:

```html
<meta name="viewport" content="initial-scale=1.0001, minimum-scale=1.0001, maximum-scale=1.0001, user-scalable=no"/>
```
